/**
 * Auto-generated TypeScript interfaces from Zod schemas
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * This file is generated by scripts/generate-api-types.ts
 * Run: pnpm generate:api-types to regenerate
 *
 * These interfaces are used by TSOA to generate the OpenAPI specification.
 * They include ALL configuration fields from the Zod schemas including
 * experiments.powerSteering and 100+ other settings.
 *
 * Note: Complex types like tuples have been simplified to be TSOA-compatible.
 */

/**
 * Experimental features that can be toggled
 * Includes: powerSteering, multiFileApplyDiff, preventFocusDisruption,
 * imageGeneration, runSlashCommand, morphFastApply
 */
export interface Experiments {
    morphFastApply?: boolean | undefined;
    powerSteering?: boolean | undefined;
    multiFileApplyDiff?: boolean | undefined;
    preventFocusDisruption?: boolean | undefined;
    imageGeneration?: boolean | undefined;
    runSlashCommand?: boolean | undefined;
}

/**
 * Provider Settings with Discriminated Union
 * This uses TypeScript discriminated unions to properly represent provider-specific fields.
 * TSOA will convert this to OpenAPI oneOf with discriminator on apiProvider field.
 */
export type ProviderSettingsDiscriminated = {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    apiKey?: string | undefined;
    anthropicBaseUrl?: string | undefined;
    anthropicUseAuthToken?: boolean | undefined;
    anthropicBeta1MContext?: boolean | undefined;
    apiProvider: "anthropic";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    claudeCodePath?: string | undefined;
    claudeCodeMaxOutputTokens?: number | undefined;
    apiProvider: "claude-code";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    glamaModelId?: string | undefined;
    glamaApiKey?: string | undefined;
    apiProvider: "glama";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    openRouterApiKey?: string | undefined;
    openRouterModelId?: string | undefined;
    openRouterBaseUrl?: string | undefined;
    openRouterSpecificProvider?: string | undefined;
    openRouterUseMiddleOutTransform?: boolean | undefined;
    openRouterProviderDataCollection?: ("allow" | "deny") | undefined;
    openRouterProviderSort?: ("price" | "throughput" | "latency") | undefined;
    openRouterZdr?: boolean | undefined;
    apiProvider: "openrouter";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    awsAccessKey?: string | undefined;
    awsSecretKey?: string | undefined;
    awsSessionToken?: string | undefined;
    awsRegion?: string | undefined;
    awsUseCrossRegionInference?: boolean | undefined;
    awsUsePromptCache?: boolean | undefined;
    awsProfile?: string | undefined;
    awsUseProfile?: boolean | undefined;
    awsApiKey?: string | undefined;
    awsUseApiKey?: boolean | undefined;
    awsCustomArn?: string | undefined;
    awsModelContextWindow?: number | undefined;
    awsBedrockEndpointEnabled?: boolean | undefined;
    awsBedrockEndpoint?: string | undefined;
    awsBedrock1MContext?: boolean | undefined;
    apiProvider: "bedrock";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    vertexKeyFile?: string | undefined;
    vertexJsonCredentials?: string | undefined;
    vertexProjectId?: string | undefined;
    vertexRegion?: string | undefined;
    enableUrlContext?: boolean | undefined;
    enableGrounding?: boolean | undefined;
    apiProvider: "vertex";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    openAiBaseUrl?: string | undefined;
    openAiApiKey?: string | undefined;
    openAiLegacyFormat?: boolean | undefined;
    openAiR1FormatEnabled?: boolean | undefined;
    openAiModelId?: string | undefined;
    openAiCustomModelInfo?: ({
        maxTokens?: (number | null) | undefined;
        maxThinkingTokens?: (number | null) | undefined;
        contextWindow: number;
        supportsImages?: boolean | undefined;
        supportsComputerUse?: boolean | undefined;
        supportsPromptCache: boolean;
        supportsVerbosity?: boolean | undefined;
        supportsReasoningBudget?: boolean | undefined;
        supportsTemperature?: boolean | undefined;
        requiredReasoningBudget?: boolean | undefined;
        supportsReasoningEffort?: boolean | undefined;
        supportedParameters?: ("max_tokens" | "temperature" | "reasoning" | "include_reasoning")[] | undefined;
        inputPrice?: number | undefined;
        outputPrice?: number | undefined;
        cacheWritesPrice?: number | undefined;
        cacheReadsPrice?: number | undefined;
        description?: string | undefined;
        reasoningEffort?: ("low" | "medium" | "high") | undefined;
        minTokensPerCachePoint?: number | undefined;
        maxCachePoints?: number | undefined;
        cachableFields?: string[] | undefined;
        displayName?: (string | null) | undefined;
        preferredIndex?: (number | null) | undefined;
        deprecated?: boolean | undefined;
        tiers?: {
            name?: ("default" | "flex" | "priority") | undefined;
            contextWindow: number;
            inputPrice?: number | undefined;
            outputPrice?: number | undefined;
            cacheWritesPrice?: number | undefined;
            cacheReadsPrice?: number | undefined;
        }[] | undefined;
    } | null) | undefined;
    openAiUseAzure?: boolean | undefined;
    azureApiVersion?: string | undefined;
    openAiStreamingEnabled?: boolean | undefined;
    openAiHostHeader?: string | undefined;
    openAiHeaders?: {
        [x: string]: string;
    } | undefined;
    apiProvider: "openai";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    ollamaModelId?: string | undefined;
    ollamaBaseUrl?: string | undefined;
    ollamaApiKey?: string | undefined;
    ollamaNumCtx?: number | undefined;
    apiProvider: "ollama";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    vsCodeLmModelSelector?: {
        vendor?: string | undefined;
        family?: string | undefined;
        version?: string | undefined;
        id?: string | undefined;
    } | undefined;
    apiProvider: "vscode-lm";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    lmStudioModelId?: string | undefined;
    lmStudioBaseUrl?: string | undefined;
    lmStudioDraftModelId?: string | undefined;
    lmStudioSpeculativeDecodingEnabled?: boolean | undefined;
    apiProvider: "lmstudio";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    geminiApiKey?: string | undefined;
    googleGeminiBaseUrl?: string | undefined;
    enableUrlContext?: boolean | undefined;
    enableGrounding?: boolean | undefined;
    apiProvider: "gemini";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    openAiNativeApiKey?: string | undefined;
    openAiNativeBaseUrl?: string | undefined;
    openAiNativeServiceTier?: ("default" | "flex" | "priority") | undefined;
    apiProvider: "openai-native";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    ovhCloudAiEndpointsApiKey?: string | undefined;
    ovhCloudAiEndpointsModelId?: string | undefined;
    ovhCloudAiEndpointsBaseUrl?: string | undefined;
    apiProvider: "ovhcloud";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    mistralApiKey?: string | undefined;
    mistralCodestralUrl?: string | undefined;
    apiProvider: "mistral";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    deepSeekBaseUrl?: string | undefined;
    deepSeekApiKey?: string | undefined;
    apiProvider: "deepseek";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    deepInfraBaseUrl?: string | undefined;
    deepInfraApiKey?: string | undefined;
    deepInfraModelId?: string | undefined;
    apiProvider: "deepinfra";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    doubaoBaseUrl?: string | undefined;
    doubaoApiKey?: string | undefined;
    apiProvider: "doubao";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    moonshotBaseUrl?: ("https://api.moonshot.ai/v1" | "https://api.moonshot.cn/v1") | undefined;
    moonshotApiKey?: string | undefined;
    apiProvider: "moonshot";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    unboundApiKey?: string | undefined;
    unboundModelId?: string | undefined;
    apiProvider: "unbound";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    requestyBaseUrl?: string | undefined;
    requestyApiKey?: string | undefined;
    requestyModelId?: string | undefined;
    apiProvider: "requesty";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiProvider: "human-relay";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    fakeAi?: unknown | undefined;
    apiProvider: "fake-ai";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    xaiApiKey?: string | undefined;
    apiProvider: "xai";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    geminiCliOAuthPath?: string | undefined;
    geminiCliProjectId?: string | undefined;
    apiProvider: "gemini-cli";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    hoodycodeToken?: string | undefined;
    hoodycodeOrganizationId?: string | undefined;
    hoodycodeModel?: string | undefined;
    openRouterSpecificProvider?: string | undefined;
    openRouterProviderDataCollection?: ("allow" | "deny") | undefined;
    openRouterProviderSort?: ("price" | "throughput" | "latency") | undefined;
    openRouterZdr?: boolean | undefined;
    hoodycodeTesterWarningsDisabledUntil?: number | undefined;
    apiProvider: "hoodycode";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    profiles?: {
        profileName?: string | undefined;
        profileId?: string | undefined;
        profileLimits?: {
            tokensPerMinute?: number | undefined;
            tokensPerHour?: number | undefined;
            tokensPerDay?: number | undefined;
            requestsPerMinute?: number | undefined;
            requestsPerHour?: number | undefined;
            requestsPerDay?: number | undefined;
        } | undefined;
    }[] | undefined;
    apiProvider: "virtual-quota-fallback";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    syntheticApiKey?: string | undefined;
    apiProvider: "synthetic";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    groqApiKey?: string | undefined;
    apiProvider: "groq";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    huggingFaceApiKey?: string | undefined;
    huggingFaceModelId?: string | undefined;
    huggingFaceInferenceProvider?: string | undefined;
    apiProvider: "huggingface";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    chutesApiKey?: string | undefined;
    apiProvider: "chutes";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    litellmBaseUrl?: string | undefined;
    litellmApiKey?: string | undefined;
    litellmModelId?: string | undefined;
    litellmUsePromptCache?: boolean | undefined;
    apiProvider: "litellm";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    cerebrasApiKey?: string | undefined;
    apiProvider: "cerebras";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    sambaNovaApiKey?: string | undefined;
    apiProvider: "sambanova";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    zaiApiKey?: string | undefined;
    zaiApiLine?: ("international_coding" | "international" | "china_coding" | "china") | undefined;
    apiProvider: "zai";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    fireworksApiKey?: string | undefined;
    apiProvider: "fireworks";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    featherlessApiKey?: string | undefined;
    apiProvider: "featherless";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    ioIntelligenceModelId?: string | undefined;
    ioIntelligenceApiKey?: string | undefined;
    apiProvider: "io-intelligence";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    qwenCodeOauthPath?: string | undefined;
    apiProvider: "qwen-code";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    apiProvider: "roo";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    vercelAiGatewayApiKey?: string | undefined;
    vercelAiGatewayModelId?: string | undefined;
    apiProvider: "vercel-ai-gateway";
} | {
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiProvider?: undefined;
}

/**
 * Complete Provider Settings (Flat)
 * Includes all provider-specific configuration options for 30+ AI providers
 * and base settings like diffEnabled, fuzzyMatchThreshold, rateLimitSeconds, etc.
 *
 * Note: This is the flat version used for backward compatibility.
 * Use ProviderSettingsDiscriminated for proper type discrimination.
 */
export interface ProviderSettings {
    apiProvider?: ("openrouter" | "vercel-ai-gateway" | "huggingface" | "litellm" | "hoodycode-openrouter" | "ovhcloud" | "chutes" | "deepinfra" | "io-intelligence" | "requesty" | "unbound" | "glama" | "ollama" | "lmstudio" | "vscode-lm" | "openai" | "fake-ai" | "human-relay" | "anthropic" | "bedrock" | "cerebras" | "chutes" | "claude-code" | "doubao" | "deepseek" | "featherless" | "fireworks" | "gemini" | "gemini-cli" | "groq" | "mistral" | "moonshot" | "openai-native" | "qwen-code" | "roo" | "hoodycode" | "gemini-cli" | "virtual-quota-fallback" | "synthetic" | "sambanova" | "vertex" | "xai" | "zai") | undefined;
    includeMaxTokens?: boolean | undefined;
    diffEnabled?: boolean | undefined;
    todoListEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    modelTemperature?: (number | null) | undefined;
    rateLimitSeconds?: number | undefined;
    consecutiveMistakeLimit?: number | undefined;
    enableReasoningEffort?: boolean | undefined;
    reasoningEffort?: (("low" | "medium" | "high") | "minimal") | undefined;
    modelMaxTokens?: number | undefined;
    modelMaxThinkingTokens?: number | undefined;
    verbosity?: ("low" | "medium" | "high") | undefined;
    taskAutoInitEnabled?: boolean | undefined;
    taskAutoInitSlashCommand?: string | undefined;
    taskAutoInitMessage?: string | undefined;
    apiModelId?: string | undefined;
    apiKey?: string | undefined;
    anthropicBaseUrl?: string | undefined;
    anthropicUseAuthToken?: boolean | undefined;
    anthropicBeta1MContext?: boolean | undefined;
    claudeCodePath?: string | undefined;
    claudeCodeMaxOutputTokens?: number | undefined;
    glamaModelId?: string | undefined;
    glamaApiKey?: string | undefined;
    openRouterApiKey?: string | undefined;
    openRouterModelId?: string | undefined;
    openRouterBaseUrl?: string | undefined;
    openRouterSpecificProvider?: string | undefined;
    openRouterUseMiddleOutTransform?: boolean | undefined;
    openRouterProviderDataCollection?: ("allow" | "deny") | undefined;
    openRouterProviderSort?: ("price" | "throughput" | "latency") | undefined;
    openRouterZdr?: boolean | undefined;
    awsAccessKey?: string | undefined;
    awsSecretKey?: string | undefined;
    awsSessionToken?: string | undefined;
    awsRegion?: string | undefined;
    awsUseCrossRegionInference?: boolean | undefined;
    awsUsePromptCache?: boolean | undefined;
    awsProfile?: string | undefined;
    awsUseProfile?: boolean | undefined;
    awsApiKey?: string | undefined;
    awsUseApiKey?: boolean | undefined;
    awsCustomArn?: string | undefined;
    awsModelContextWindow?: number | undefined;
    awsBedrockEndpointEnabled?: boolean | undefined;
    awsBedrockEndpoint?: string | undefined;
    awsBedrock1MContext?: boolean | undefined;
    vertexKeyFile?: string | undefined;
    vertexJsonCredentials?: string | undefined;
    vertexProjectId?: string | undefined;
    vertexRegion?: string | undefined;
    enableUrlContext?: boolean | undefined;
    enableGrounding?: boolean | undefined;
    openAiBaseUrl?: string | undefined;
    openAiApiKey?: string | undefined;
    openAiLegacyFormat?: boolean | undefined;
    openAiR1FormatEnabled?: boolean | undefined;
    openAiModelId?: string | undefined;
    openAiCustomModelInfo?: ({
        maxTokens?: (number | null) | undefined;
        maxThinkingTokens?: (number | null) | undefined;
        contextWindow: number;
        supportsImages?: boolean | undefined;
        supportsComputerUse?: boolean | undefined;
        supportsPromptCache: boolean;
        supportsVerbosity?: boolean | undefined;
        supportsReasoningBudget?: boolean | undefined;
        supportsTemperature?: boolean | undefined;
        requiredReasoningBudget?: boolean | undefined;
        supportsReasoningEffort?: boolean | undefined;
        supportedParameters?: ("max_tokens" | "temperature" | "reasoning" | "include_reasoning")[] | undefined;
        inputPrice?: number | undefined;
        outputPrice?: number | undefined;
        cacheWritesPrice?: number | undefined;
        cacheReadsPrice?: number | undefined;
        description?: string | undefined;
        reasoningEffort?: ("low" | "medium" | "high") | undefined;
        minTokensPerCachePoint?: number | undefined;
        maxCachePoints?: number | undefined;
        cachableFields?: string[] | undefined;
        displayName?: (string | null) | undefined;
        preferredIndex?: (number | null) | undefined;
        deprecated?: boolean | undefined;
        tiers?: {
            name?: ("default" | "flex" | "priority") | undefined;
            contextWindow: number;
            inputPrice?: number | undefined;
            outputPrice?: number | undefined;
            cacheWritesPrice?: number | undefined;
            cacheReadsPrice?: number | undefined;
        }[] | undefined;
    } | null) | undefined;
    openAiUseAzure?: boolean | undefined;
    azureApiVersion?: string | undefined;
    openAiStreamingEnabled?: boolean | undefined;
    openAiHostHeader?: string | undefined;
    openAiHeaders?: {
        [x: string]: string;
    } | undefined;
    ollamaModelId?: string | undefined;
    ollamaBaseUrl?: string | undefined;
    ollamaApiKey?: string | undefined;
    ollamaNumCtx?: number | undefined;
    vsCodeLmModelSelector?: {
        vendor?: string | undefined;
        family?: string | undefined;
        version?: string | undefined;
        id?: string | undefined;
    } | undefined;
    lmStudioModelId?: string | undefined;
    lmStudioBaseUrl?: string | undefined;
    lmStudioDraftModelId?: string | undefined;
    lmStudioSpeculativeDecodingEnabled?: boolean | undefined;
    geminiApiKey?: string | undefined;
    googleGeminiBaseUrl?: string | undefined;
    geminiCliOAuthPath?: string | undefined;
    geminiCliProjectId?: string | undefined;
    hoodycodeToken?: string | undefined;
    hoodycodeOrganizationId?: string | undefined;
    hoodycodeModel?: string | undefined;
    hoodycodeTesterWarningsDisabledUntil?: number | undefined;
    profiles?: {
        profileName?: string | undefined;
        profileId?: string | undefined;
        profileLimits?: {
            tokensPerMinute?: number | undefined;
            tokensPerHour?: number | undefined;
            tokensPerDay?: number | undefined;
            requestsPerMinute?: number | undefined;
            requestsPerHour?: number | undefined;
            requestsPerDay?: number | undefined;
        } | undefined;
    }[] | undefined;
    syntheticApiKey?: string | undefined;
    openAiNativeApiKey?: string | undefined;
    openAiNativeBaseUrl?: string | undefined;
    openAiNativeServiceTier?: ("default" | "flex" | "priority") | undefined;
    mistralApiKey?: string | undefined;
    mistralCodestralUrl?: string | undefined;
    deepSeekBaseUrl?: string | undefined;
    deepSeekApiKey?: string | undefined;
    deepInfraBaseUrl?: string | undefined;
    deepInfraApiKey?: string | undefined;
    deepInfraModelId?: string | undefined;
    doubaoBaseUrl?: string | undefined;
    doubaoApiKey?: string | undefined;
    moonshotBaseUrl?: ("https://api.moonshot.ai/v1" | "https://api.moonshot.cn/v1") | undefined;
    moonshotApiKey?: string | undefined;
    unboundApiKey?: string | undefined;
    unboundModelId?: string | undefined;
    requestyBaseUrl?: string | undefined;
    requestyApiKey?: string | undefined;
    requestyModelId?: string | undefined;
    fakeAi?: unknown | undefined;
    xaiApiKey?: string | undefined;
    groqApiKey?: string | undefined;
    huggingFaceApiKey?: string | undefined;
    huggingFaceModelId?: string | undefined;
    huggingFaceInferenceProvider?: string | undefined;
    chutesApiKey?: string | undefined;
    litellmBaseUrl?: string | undefined;
    litellmApiKey?: string | undefined;
    litellmModelId?: string | undefined;
    litellmUsePromptCache?: boolean | undefined;
    cerebrasApiKey?: string | undefined;
    sambaNovaApiKey?: string | undefined;
    zaiApiKey?: string | undefined;
    zaiApiLine?: ("international_coding" | "international" | "china_coding" | "china") | undefined;
    fireworksApiKey?: string | undefined;
    featherlessApiKey?: string | undefined;
    ioIntelligenceModelId?: string | undefined;
    ioIntelligenceApiKey?: string | undefined;
    qwenCodeOauthPath?: string | undefined;
    vercelAiGatewayApiKey?: string | undefined;
    vercelAiGatewayModelId?: string | undefined;
    codeIndexOpenAiKey?: string | undefined;
    codeIndexQdrantApiKey?: string | undefined;
    codebaseIndexOpenAiCompatibleBaseUrl?: string | undefined;
    codebaseIndexOpenAiCompatibleApiKey?: string | undefined;
    codebaseIndexOpenAiCompatibleModelDimension?: number | undefined;
    codebaseIndexGeminiApiKey?: string | undefined;
    codebaseIndexMistralApiKey?: string | undefined;
    codebaseIndexVercelAiGatewayApiKey?: string | undefined;
    ovhCloudAiEndpointsApiKey?: string | undefined;
    ovhCloudAiEndpointsModelId?: string | undefined;
    ovhCloudAiEndpointsBaseUrl?: string | undefined;
}

/**
 * Complete Global Settings
 * Includes all extension settings (100+ fields) including:
 * - experiments object (with powerSteering)
 * - autoApproval settings
 * - terminal settings
 * - browser settings
 * - MCP settings
 * - and much more
 */
export interface GlobalSettings {
    currentApiConfigName?: string | undefined;
    listApiConfigMeta?: {
        id: string;
        name: string;
        apiProvider?: ("openrouter" | "vercel-ai-gateway" | "huggingface" | "litellm" | "hoodycode-openrouter" | "ovhcloud" | "chutes" | "deepinfra" | "io-intelligence" | "requesty" | "unbound" | "glama" | "ollama" | "lmstudio" | "vscode-lm" | "openai" | "fake-ai" | "human-relay" | "anthropic" | "bedrock" | "cerebras" | "chutes" | "claude-code" | "doubao" | "deepseek" | "featherless" | "fireworks" | "gemini" | "gemini-cli" | "groq" | "mistral" | "moonshot" | "openai-native" | "qwen-code" | "roo" | "hoodycode" | "gemini-cli" | "virtual-quota-fallback" | "synthetic" | "sambanova" | "vertex" | "xai" | "zai") | undefined;
        modelId?: string | undefined;
    }[] | undefined;
    pinnedApiConfigs?: {
        [x: string]: boolean;
    } | undefined;
    lastShownAnnouncementId?: string | undefined;
    customInstructions?: string | undefined;
    taskHistory?: {
        id: string;
        rootTaskId?: string | undefined;
        parentTaskId?: string | undefined;
        number: number;
        ts: number;
        task: string;
        tokensIn: number;
        tokensOut: number;
        cacheWrites?: number | undefined;
        cacheReads?: number | undefined;
        totalCost: number;
        contextTokens?: number | undefined;
        size?: number | undefined;
        workspace?: string | undefined;
        isFavorited?: boolean | undefined;
        fileNotfound?: boolean | undefined;
        mode?: string | undefined;
        modelId?: string | undefined;
        modelProvider?: string | undefined;
        profileName?: string | undefined;
        sourceTaskId?: string | undefined;
        forkFromMessageTs?: number | undefined;
        forkTimestamp?: number | undefined;
        status?: ("running" | "interactive" | "resumable" | "idle" | "completed") | undefined;
    }[] | undefined;
    dismissedUpsells?: string[] | undefined;
    openRouterImageApiKey?: string | undefined;
    openRouterImageGenerationSelectedModel?: string | undefined;
    hoodyCodeImageApiKey?: string | undefined;
    condensingApiConfigId?: string | undefined;
    customCondensingPrompt?: string | undefined;
    digestEnabled?: boolean | undefined;
    digestProfileId?: string | undefined;
    autoDigestEnabled?: boolean | undefined;
    digestMaxLength?: number | undefined;
    customDigestPrompt?: string | undefined;
    digestTaskOverrides?: {
        [x: string]: {
            enabled: boolean;
            maxLength?: number | undefined;
            profileId?: string | undefined;
        };
    } | undefined;
    autoApprovalEnabled?: boolean | undefined;
    alwaysAllowReadOnly?: boolean | undefined;
    alwaysAllowReadOnlyOutsideWorkspace?: boolean | undefined;
    alwaysAllowWrite?: boolean | undefined;
    alwaysAllowWriteOutsideWorkspace?: boolean | undefined;
    alwaysAllowWriteProtected?: boolean | undefined;
    writeDelayMs?: number | undefined;
    alwaysAllowBrowser?: boolean | undefined;
    alwaysApproveResubmit?: boolean | undefined;
    requestDelaySeconds?: number | undefined;
    alwaysAllowMcp?: boolean | undefined;
    alwaysAllowModeSwitch?: boolean | undefined;
    alwaysAllowSubtasks?: boolean | undefined;
    alwaysAllowExecute?: boolean | undefined;
    alwaysAllowFollowupQuestions?: boolean | undefined;
    followupAutoApproveTimeoutMs?: number | undefined;
    alwaysAllowUpdateTodoList?: boolean | undefined;
    allowedCommands?: string[] | undefined;
    deniedCommands?: string[] | undefined;
    commandExecutionTimeout?: number | undefined;
    commandTimeoutAllowlist?: string[] | undefined;
    preventCompletionWithOpenTodos?: boolean | undefined;
    allowedMaxRequests?: (number | null) | undefined;
    allowedMaxCost?: (number | null) | undefined;
    autoCondenseContext?: boolean | undefined;
    autoCondenseContextPercent?: number | undefined;
    maxConcurrentFileReads?: number | undefined;
    allowVeryLargeReads?: boolean | undefined;
    includeDiagnosticMessages?: boolean | undefined;
    maxDiagnosticMessages?: number | undefined;
    browserToolEnabled?: boolean | undefined;
    browserViewportSize?: string | undefined;
    showAutoApproveMenu?: boolean | undefined;
    showTaskTimeline?: boolean | undefined;
    showTimestamps?: boolean | undefined;
    hideCostBelowThreshold?: number | undefined;
    localWorkflowToggles?: {
        [x: string]: boolean;
    } | undefined;
    globalWorkflowToggles?: {
        [x: string]: boolean;
    } | undefined;
    localRulesToggles?: {
        [x: string]: boolean;
    } | undefined;
    globalRulesToggles?: {
        [x: string]: boolean;
    } | undefined;
    screenshotQuality?: number | undefined;
    remoteBrowserEnabled?: boolean | undefined;
    remoteBrowserHost?: string | undefined;
    cachedChromeHostUrl?: string | undefined;
    enableCheckpoints?: boolean | undefined;
    ttsEnabled?: boolean | undefined;
    ttsSpeed?: number | undefined;
    soundEnabled?: boolean | undefined;
    soundVolume?: number | undefined;
    systemNotificationsEnabled?: boolean | undefined;
    maxOpenTabsContext?: number | undefined;
    maxWorkspaceFiles?: number | undefined;
    showRooIgnoredFiles?: boolean | undefined;
    maxReadFileLine?: number | undefined;
    maxImageFileSize?: number | undefined;
    maxTotalImageSize?: number | undefined;
    terminalOutputLineLimit?: number | undefined;
    terminalOutputCharacterLimit?: number | undefined;
    terminalShellIntegrationTimeout?: number | undefined;
    terminalShellIntegrationDisabled?: boolean | undefined;
    terminalCommandDelay?: number | undefined;
    terminalPowershellCounter?: boolean | undefined;
    terminalZshClearEolMark?: boolean | undefined;
    terminalZshOhMy?: boolean | undefined;
    terminalZshP10k?: boolean | undefined;
    terminalZdotdir?: boolean | undefined;
    terminalCompressProgressBar?: boolean | undefined;
    diagnosticsEnabled?: boolean | undefined;
    rateLimitSeconds?: number | undefined;
    diffEnabled?: boolean | undefined;
    fuzzyMatchThreshold?: number | undefined;
    experiments?: {
        morphFastApply?: boolean | undefined;
        powerSteering?: boolean | undefined;
        multiFileApplyDiff?: boolean | undefined;
        preventFocusDisruption?: boolean | undefined;
        imageGeneration?: boolean | undefined;
        runSlashCommand?: boolean | undefined;
    } | undefined;
    morphApiKey?: string | undefined;
    fastApplyModel?: ("auto" | "morph/morph-v3-fast" | "morph/morph-v3-large" | "relace/relace-apply-3") | undefined;
    codebaseIndexModels?: {
        openai?: {
            [x: string]: {
                dimension: number;
            };
        } | undefined;
        ollama?: {
            [x: string]: {
                dimension: number;
            };
        } | undefined;
        "openai-compatible"?: {
            [x: string]: {
                dimension: number;
            };
        } | undefined;
        gemini?: {
            [x: string]: {
                dimension: number;
            };
        } | undefined;
        mistral?: {
            [x: string]: {
                dimension: number;
            };
        } | undefined;
        "vercel-ai-gateway"?: {
            [x: string]: {
                dimension: number;
            };
        } | undefined;
    } | undefined;
    codebaseIndexConfig?: {
        codebaseIndexEnabled?: boolean | undefined;
        codebaseIndexQdrantUrl?: string | undefined;
        codebaseIndexEmbedderProvider?: ("openai" | "ollama" | "openai-compatible" | "gemini" | "mistral" | "vercel-ai-gateway") | undefined;
        codebaseIndexEmbedderBaseUrl?: string | undefined;
        codebaseIndexEmbedderModelId?: string | undefined;
        codebaseIndexEmbedderModelDimension?: number | undefined;
        codebaseIndexSearchMinScore?: number | undefined;
        codebaseIndexSearchMaxResults?: number | undefined;
        codebaseIndexOpenAiCompatibleBaseUrl?: string | undefined;
        codebaseIndexOpenAiCompatibleModelDimension?: number | undefined;
    } | undefined;
    language?: ("ar" | "cs" | "th" | "uk" | "ca" | "de" | "en" | "es" | "fr" | "hi" | "id" | "it" | "ja" | "ko" | "nl" | "pl" | "pt-BR" | "ru" | "tr" | "vi" | "zh-CN" | "zh-TW") | undefined;
    telemetrySetting?: ("unset" | "enabled" | "disabled") | undefined;
    mcpEnabled?: boolean | undefined;
    enableMcpServerCreation?: boolean | undefined;
    mcpMarketplaceCatalog?: any | undefined;
    mode?: string | undefined;
    modeApiConfigs?: {
        [x: string]: string;
    } | undefined;
    customModes?: any[] | undefined;
    customModePrompts?: {
        [x: string]: {
            roleDefinition?: string | undefined;
            whenToUse?: string | undefined;
            description?: string | undefined;
            customInstructions?: string | undefined;
        } | undefined;
    } | undefined;
    customSupportPrompts?: {
        [x: string]: string | undefined;
    } | undefined;
    enhancementApiConfigId?: string | undefined;
    dismissedNotificationIds?: string[] | undefined;
    commitMessageApiConfigId?: string | undefined;
    terminalCommandApiConfigId?: string | undefined;
    ghostServiceSettings?: {
        enableAutoTrigger?: boolean | undefined;
        autoTriggerDelay?: number | undefined;
        enableQuickInlineTaskKeybinding?: boolean | undefined;
        enableSmartInlineTaskKeybinding?: boolean | undefined;
        showGutterAnimation?: boolean | undefined;
    } | undefined;
    includeTaskHistoryInEnhance?: boolean | undefined;
    historyPreviewCollapsed?: boolean | undefined;
    reasoningBlockCollapsed?: boolean | undefined;
    profileThresholds?: {
        [x: string]: number;
    } | undefined;
    hasOpenedModeSelector?: boolean | undefined;
    lastModeExportPath?: string | undefined;
    lastModeImportPath?: string | undefined;
}

// ============================================================================
// UI Message Types
// ============================================================================

/**
 * Ask types - Messages where the agent requests user interaction/approval
 *
 * These represent different scenarios where the assistant needs user input:
 * - followup: Clarifying question to gather more information
 * - command: Permission to execute a terminal/shell command
 * - completion_result: Task completed, awaiting feedback or new task
 * - tool: Permission to use a tool for file operations
 * - api_req_failed: API request failed, asking whether to retry
 * - resume_task: Confirmation to resume a paused task
 * - browser_action_launch: Permission to open/interact with browser
 * - use_mcp_server: Permission to use MCP server functionality
 * - and more...
 */
export type ClineAsk = "followup" | "command" | "command_output" | "completion_result" | "tool" | "api_req_failed" | "resume_task" | "resume_completed_task" | "mistake_limit_reached" | "browser_action_launch" | "use_mcp_server" | "auto_approval_max_req_reached" | "payment_required_prompt" | "invalid_model" | "report_bug" | "condense"

/**
 * Say types - Informational messages from the agent
 *
 * These represent different kinds of communication from the LLM:
 * - text: General text message or assistant response
 * - api_req_started: API request has been initiated
 * - api_req_finished: API request completed successfully
 * - completion_result: Final result of task completion
 * - command_output: Output from an executed command
 * - checkpoint_saved: Checkpoint has been saved
 * - reasoning: Assistant's reasoning/thought process
 * - and more...
 */
export type ClineSay = "error" | "api_req_started" | "api_req_finished" | "api_req_retried" | "api_req_retry_delayed" | "api_req_deleted" | "text" | "image" | "reasoning" | "completion_result" | "user_feedback" | "user_feedback_diff" | "command_output" | "shell_integration_warning" | "browser_action" | "browser_action_result" | "mcp_server_request_started" | "mcp_server_response" | "subtask_result" | "checkpoint_saved" | "rooignore_error" | "diff_error" | "condense_context" | "condense_context_error" | "codebase_search_result" | "user_edit_todos"

/**
 * Tool progress status
 * Used to show progress indicators during tool execution
 */
export type ToolProgressStatus = {
    icon?: string | undefined;
    text?: string | undefined;
}

/**
 * Context condensation result
 * Information about context summarization/compression
 */
export type ContextCondense = {
    cost: number;
    prevContextTokens: number;
    newContextTokens: number;
    summary: string;
}

/**
 * ClineMessage - Complete UI message structure
 *
 * This is a discriminated union based on the 'type' field:
 * - type: "ask" → Message requesting user interaction (uses 'ask' field)
 * - type: "say" → Informational message (uses 'say' field)
 *
 * Common fields:
 * - ts: Message timestamp
 * - text: Message content
 * - images: Optional image attachments
 * - partial: Whether message is still streaming
 *
 * Special fields:
 * - progressStatus: Tool execution progress
 * - contextCondense: Context condensation info
 * - checkpoint: Git checkpoint metadata
 * - reasoning: Assistant's reasoning process
 */
export type ClineMessage = {
    ts: number;
    type: "ask" | "say";
    ask?: ("followup" | "command" | "command_output" | "completion_result" | "tool" | "api_req_failed" | "resume_task" | "resume_completed_task" | "mistake_limit_reached" | "browser_action_launch" | "use_mcp_server" | "auto_approval_max_req_reached" | "payment_required_prompt" | "invalid_model" | "report_bug" | "condense") | undefined;
    say?: ("error" | "api_req_started" | "api_req_finished" | "api_req_retried" | "api_req_retry_delayed" | "api_req_deleted" | "text" | "image" | "reasoning" | "completion_result" | "user_feedback" | "user_feedback_diff" | "command_output" | "shell_integration_warning" | "browser_action" | "browser_action_result" | "mcp_server_request_started" | "mcp_server_response" | "subtask_result" | "checkpoint_saved" | "rooignore_error" | "diff_error" | "condense_context" | "condense_context_error" | "codebase_search_result" | "user_edit_todos") | undefined;
    text?: string | undefined;
    images?: string[] | undefined;
    partial?: boolean | undefined;
    reasoning?: string | undefined;
    conversationHistoryIndex?: number | undefined;
    checkpoint?: {
        [x: string]: unknown;
    } | undefined;
    progressStatus?: {
        icon?: string | undefined;
        text?: string | undefined;
    } | undefined;
    contextCondense?: {
        cost: number;
        prevContextTokens: number;
        newContextTokens: number;
        summary: string;
    } | undefined;
    isProtected?: boolean | undefined;
    apiProtocol?: ("openai" | "anthropic") | undefined;
    isAnswered?: boolean | undefined;
    digest?: string | undefined;
    digestMetadata?: {
        generatedAt: number;
        profileId: string;
        tokensUsed?: number | undefined;
        maxLength: number;
    } | undefined;
    metadata?: {
        gpt5?: {
            previous_response_id?: string | undefined;
            instructions?: string | undefined;
            reasoning_summary?: string | undefined;
        } | undefined;
        hoodyCode?: {
            commitRange?: {
                from: string;
                fromTimeStamp?: number | undefined;
                to: string;
            } | undefined;
        } | undefined;
        general?: {
            modelId?: string | undefined;
            provider?: string | undefined;
            profileName?: string | undefined;
            profileId?: string | undefined;
            mode?: string | undefined;
            tokensIn?: number | undefined;
            tokensOut?: number | undefined;
            cacheWrites?: number | undefined;
            cacheReads?: number | undefined;
            cost?: number | undefined;
            cumulativeCost?: number | undefined;
            cumulativeTokensIn?: number | undefined;
            cumulativeTokensOut?: number | undefined;
        } | undefined;
    } | undefined;
}
